# Generated by Django 2.2.1 on 2019-05-30 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_itens', models.TextField()),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tracking_code', models.CharField(max_length=200)),
                ('purchase_amount', models.CharField(max_length=200)),
                ('tracking_mode', models.CharField(choices=[('0414', 'SEDEX'), ('04510', 'PAC'), ('0215', 'SEDEX10')], max_length=6)),
                ('shippng_time', models.CharField(max_length=2)),
            ],
        ),
    ]
