# Generated by Django 2.2.1 on 2019-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_description', models.CharField(max_length=200)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('product_width', models.DecimalField(decimal_places=2, max_digits=3)),
                ('product_length', models.DecimalField(decimal_places=2, max_digits=3)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('produtc_status', models.CharField(max_length=40)),
                ('product_quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tracking_code',
            field=models.CharField(max_length=40),
        ),
    ]
