# Generated by Django 2.2.1 on 2019-05-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20190530_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_length',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
