# Generated by Django 2.2.1 on 2019-05-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20190530_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_itens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Product'),
        ),
    ]
