# Generated by Django 2.2.1 on 2019-05-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20190530_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='produtc_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='shippng_time',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tracking_mode',
            field=models.CharField(blank=True, choices=[('0414', 'SEDEX'), ('04510', 'PAC'), ('0215', 'SEDEX10')], max_length=6),
        ),
    ]
