# Generated by Django 2.2.1 on 2019-05-31 21:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_auto_20190531_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('cogio_rastreio', models.CharField(blank=True, max_length=40, null=True)),
                ('total_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metodo_envio', models.CharField(blank=True, choices=[('0414', 'SEDEX'), ('04510', 'PAC'), ('0215', 'SEDEX10')], max_length=6, null=True)),
                ('tempo_envio', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('descricao', models.CharField(max_length=200)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('comprimento', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Compra')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_itens',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
