# Generated by Django 2.2.1 on 2019-06-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_auto_20190531_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='produtos',
            field=models.ManyToManyField(to='compras.Produto'),
        ),
    ]
