# Generated by Django 2.2.1 on 2019-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20190601_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_compra',
            field=models.DateTimeField(),
        ),
    ]
