# Generated by Django 2.2.1 on 2019-06-03 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_auto_20190603_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
