# Generated by Django 2.2.1 on 2019-06-16 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_auto_20190603_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='total_compra',
            new_name='total_produtos',
        ),
        migrations.AddField(
            model_name='compra',
            name='categoria_compra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='data_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='observacoes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='qtd_produtos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_frete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
